### PR TITLE
Compatibility with Grails 2.2.0

### PR DESCRIPTION
**Pull request by owahlen**
I have made some changes to make the plugin compatible with Grails 2.2.0.
I had the problem that I received a VerifyError in the taglib.
This was solved by simply moving two private inner classes outside of the taglib.
I am not sure if this is the best solution but at least it works.
Maybe have a look for yourself.

### CODE REVIEW

**Comment by henadzit** [comment]
Thank you for pointing out the issue. Actually I can't reproduce the issue. But I applied your changes just in case.

Thanks,
Gennady

**Comment by henadzit** [comment]
Please check out version 0.4.2.

**Comment by owahlen** [comment]
Hi gtsarik,
unfortunately with version 0.4.2 it still does not work.
If you have a closer look at my code you can see that the HierarchyLevelType and the HierarchyLevelHolder are not inside the BrowserTagLib class (i.e. they are no longer inner classes).
I agree that it is not nice to put these classes into the taglib file.
Maybe you can move these two classes into src/groovy/org/geeks/browserdetection/...
I am pretty sure that this will solve the issue, too.
Would you mind giving that a try?

**Comment by henadzit** [comment]
Ok, I see. It was my bad.

Could you please check out the latest source from git and try again? Please build and install the plugin manually. If it works for you, I will release 0.4.3.

**Comment by owahlen** [comment]
I have just cloned the latest git sources and used your code as an inline plugin.
This works perfectly now.
It would be nice if you could release version 0.4.3 from this code.
Thank you again for your support.

**Comment by henadzit** [comment]
Version 0.4.3 has been released.

Thanks

**Pull request closed without merging**
